from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ProactiveResilienceStore(Protocol):
    """Minimal async KV operations for proactive resilience (implemented in the host)."""

    async def exists(self, key: str) -> bool: ...
    async def get(self, key: str) -> bytes | None: ...
    async def setex(
        self, key: str, seconds: float | int, value: bytes | str
    ) -> Any: ...
    async def incr(self, key: str) -> int: ...
    async def delete(self, key: str) -> Any: ...
    async def expire(self, key: str, seconds: float | int) -> Any: ...
